export const browserCoreExamples = [
  "medha browser status",
  "medha browser start",
  "medha browser stop",
  "medha browser tabs",
  "medha browser open https://example.com",
  "medha browser focus abcd1234",
  "medha browser close abcd1234",
  "medha browser screenshot",
  "medha browser screenshot --full-page",
  "medha browser screenshot --ref 12",
  "medha browser snapshot",
  "medha browser snapshot --format aria --limit 200",
  "medha browser snapshot --efficient",
  "medha browser snapshot --labels",
];

export const browserActionExamples = [
  "medha browser navigate https://example.com",
  "medha browser resize 1280 720",
  "medha browser click 12 --double",
  'medha browser type 23 "hello" --submit',
  "medha browser press Enter",
  "medha browser hover 44",
  "medha browser drag 10 11",
  "medha browser select 9 OptionA OptionB",
  "medha browser upload /tmp/medha/uploads/file.pdf",
  'medha browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "medha browser dialog --accept",
  'medha browser wait --text "Done"',
  "medha browser evaluate --fn '(el) => el.textContent' --ref 7",
  "medha browser console --level error",
  "medha browser pdf",
];
